-- Criando o Banco de Dados
CREATE DATABASE IF NOT EXISTS sistema_clinico;
USE sistema_clinico;

-- TABELAS DIMENSIONAIS (D_)

-- Clínica
CREATE TABLE D_CLINICA (
    CLINICA_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLINICA_NOME VARCHAR(255) NOT NULL,
    CLINICA_CNPJ VARCHAR(18) NOT NULL,
    CLINICA_INSCRICAO_ESTADUAL VARCHAR(20),
    CLINICA_TELEFONE VARCHAR(15),
    CLINICA_EMAIL VARCHAR(255),
    CLINICA_RESPONSAVEL VARCHAR(255) NOT NULL,
    CLINICA_DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    CLINICA_DATA_ATUALIZACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Endereço
CREATE TABLE D_ENDERECO (
    ENDERECO_ID INT AUTO_INCREMENT PRIMARY KEY,
    END_LOGRADOURO VARCHAR(255) NOT NULL,
    END_NUMERO VARCHAR(10) NOT NULL,
    END_COMPLEMENTO VARCHAR(100),
    END_BAIRRO VARCHAR(100) NOT NULL,
    END_CIDADE VARCHAR(100) NOT NULL,
    END_ESTADO CHAR(2) NOT NULL,
    END_CEP VARCHAR(9) NOT NULL,
    END_PAIS VARCHAR(100) NOT NULL,
    ENDERECO_DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ENDERECO_DATA_ATUALIZACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Sistema
CREATE TABLE D_SISTEMA (
    SISTEMA_ID INT AUTO_INCREMENT PRIMARY KEY,
    SISTEMA_NOME VARCHAR(255) NOT NULL,
    SISTEMA_DESCRICAO TEXT,
    SISTEMA_VERSAO VARCHAR(20),
    SISTEMA_DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    SISTEMA_DATA_ATUALIZACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Usuário Perfil
CREATE TABLE D_USUARIO_PERFIL (
    USUARIO_PERFIL_ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_PERFIL_TIPO VARCHAR(50) NOT NULL,
    USUARIO_PERFIL_DESCRICAO TEXT,
    USUARIO_PERFIL_DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    USUARIO_PERFIL_DATA_ATUALIZACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Questionário
CREATE TABLE D_QUESTIONARIO (
    QUESTIONARIO_ID INT AUTO_INCREMENT PRIMARY KEY,
    QUESTIONARIO_NOME VARCHAR(255) NOT NULL,
    QUESTIONARIO_DESCRICAO TEXT,
    QUESTIONARIO_NOTA INT,
    QUESTIONARIO_DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    QUESTIONARIO_DATA_ATUALIZACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Reabilitação 
CREATE TABLE D_REABILITACAO (
    REABILITACAO_ID INT AUTO_INCREMENT PRIMARY KEY,
    REABILITACAO_TIPO VARCHAR(100) NOT NULL,
    REABILITACAO_DESCRICAO TEXT,
    REABILITACAO_DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    REABILITACAO_DATA_ATUALIZACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- TABELA FATO (F_)

-- Usuário
CREATE TABLE F_USUARIO (
    USUARIO_ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_NOME VARCHAR(255) NOT NULL,
    USUARIO_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USUARIO_CIRURGIA VARCHAR(255),
    USUARIO_CPF CHAR(14) NOT NULL UNIQUE,
    USUARIO_GENERO VARCHAR(50) NOT NULL,
    USUARIO_SENHA VARCHAR(255) NOT NULL, 
    USUARIO_DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    USUARIO_DATA_ATUALIZACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    F_USUARIO_ID_USUARIO_PERFIL INT NOT NULL,
    F_USUARIO_ID_CLINICA INT NULL,
    F_USUARIO_ID_REABILITACAO INT,
    FOREIGN KEY (F_USUARIO_ID_USUARIO_PERFIL) REFERENCES D_USUARIO_PERFIL(USUARIO_PERFIL_ID),
    FOREIGN KEY (F_USUARIO_ID_CLINICA) REFERENCES D_CLINICA(CLINICA_ID),
    FOREIGN KEY (F_USUARIO_ID_REABILITACAO) REFERENCES D_REABILITACAO(REABILITACAO_ID)
);

-- Relacionamento entre Clínica e Endereço
CREATE TABLE REL_CLINICA_ENDERECO (
    REL_CLINICA_ENDERECO_ID INT AUTO_INCREMENT PRIMARY KEY,
    F_REL_ID_CLINICA INT NOT NULL,
    F_REL_ID_ENDERECO INT NOT NULL,
    FOREIGN KEY (F_REL_ID_CLINICA) REFERENCES D_CLINICA(CLINICA_ID),
    FOREIGN KEY (F_REL_ID_ENDERECO) REFERENCES D_ENDERECO(ENDERECO_ID)
);

-- Relacionamento entre Sistema e Clínica
CREATE TABLE REL_SISTEMA_CLINICA (
    REL_SISTEMA_CLINICA_ID INT AUTO_INCREMENT PRIMARY KEY,
    F_REL_ID_SISTEMA INT NOT NULL,
    F_REL_ID_CLINICA INT NOT NULL,
    FOREIGN KEY (F_REL_ID_SISTEMA) REFERENCES D_SISTEMA(SISTEMA_ID),
    FOREIGN KEY (F_REL_ID_CLINICA) REFERENCES D_CLINICA(CLINICA_ID)
);

-- Relacionamento entre Sistema e Usuário
CREATE TABLE REL_SISTEMA_USUARIO (
    REL_SISTEMA_USUARIO_ID INT AUTO_INCREMENT PRIMARY KEY,
    F_REL_ID_SISTEMA INT NOT NULL,
    F_REL_ID_USUARIO INT NOT NULL,
    FOREIGN KEY (F_REL_ID_SISTEMA) REFERENCES D_SISTEMA(SISTEMA_ID),
    FOREIGN KEY (F_REL_ID_USUARIO) REFERENCES F_USUARIO(USUARIO_ID)
);

-- Relacionamento entre Usuário e Questionário
CREATE TABLE REL_USUARIO_QUESTIONARIO (
    REL_USUARIO_QUESTIONARIO_ID INT AUTO_INCREMENT PRIMARY KEY,
    F_REL_ID_USUARIO INT NOT NULL,
    F_REL_ID_QUESTIONARIO INT NOT NULL,
    FOREIGN KEY (F_REL_ID_USUARIO) REFERENCES F_USUARIO(USUARIO_ID),
    FOREIGN KEY (F_REL_ID_QUESTIONARIO) REFERENCES D_QUESTIONARIO(QUESTIONARIO_ID)
);

-- Inserções de dados iniciais

-- Clínica
INSERT INTO D_CLINICA (CLINICA_NOME, CLINICA_CNPJ, CLINICA_INSCRICAO_ESTADUAL, CLINICA_TELEFONE, CLINICA_EMAIL, CLINICA_RESPONSAVEL) 
VALUES ('Clinica Teste', '12345678000195', '123456789', '(11)99999-9999', 'contato@clinica.com', 'Responsavel Teste');

-- Endereço
INSERT INTO D_ENDERECO (END_LOGRADOURO, END_NUMERO, END_COMPLEMENTO, END_BAIRRO, END_CIDADE, END_ESTADO, END_CEP, END_PAIS) 
VALUES ('Rua Teste', '123', 'Sala 1', 'Bairro Teste', 'Cidade Teste', 'SP', '12345-678', 'Brasil');

-- Sistema
INSERT INTO D_SISTEMA (SISTEMA_NOME, SISTEMA_DESCRICAO, SISTEMA_VERSAO) 
VALUES ('Sistema Teste', 'Descrição do Sistema', '1.0');

-- Perfil
INSERT INTO D_USUARIO_PERFIL (USUARIO_PERFIL_TIPO, USUARIO_PERFIL_DESCRICAO) 
VALUES ('Administrador', 'Acesso total'), ('Médico', 'Acesso do perfil médico'),('Paciente', 'Acesso do perfil paciente');

-- Questionário
INSERT INTO D_QUESTIONARIO (QUESTIONARIO_NOME, QUESTIONARIO_DESCRICAO, QUESTIONARIO_NOTA) 
VALUES ('Questionário Teste', 'Descrição do Questionário', 10);

-- Reabilitação
INSERT INTO D_REABILITACAO (REABILITACAO_TIPO, REABILITACAO_DESCRICAO) 
VALUES ('Tipo A', 'Descrição A');

-- Usuário
INSERT INTO F_USUARIO (USUARIO_NOME, USUARIO_EMAIL, USUARIO_CIRURGIA, USUARIO_CPF, USUARIO_GENERO, USUARIO_SENHA, F_USUARIO_ID_USUARIO_PERFIL, F_USUARIO_ID_CLINICA, F_USUARIO_ID_REABILITACAO) 
VALUES ('Administrador', 'admin@teste.com', NULL, '111.111.111-11', 'Masculino', '$2b$10$HASHDA.SENHA', 1, 1, 1);

-- Relacionamentos
INSERT INTO REL_CLINICA_ENDERECO (F_REL_ID_CLINICA, F_REL_ID_ENDERECO) VALUES (1, 1);
INSERT INTO REL_SISTEMA_CLINICA (F_REL_ID_SISTEMA, F_REL_ID_CLINICA) VALUES (1, 1);
INSERT INTO REL_SISTEMA_USUARIO (F_REL_ID_SISTEMA, F_REL_ID_USUARIO) VALUES (1, 1);
INSERT INTO REL_USUARIO_QUESTIONARIO (F_REL_ID_USUARIO, F_REL_ID_QUESTIONARIO) VALUES (1, 1);

-- Usuários padrão para testes
INSERT INTO F_USUARIO (
    USUARIO_NOME, 
    USUARIO_EMAIL, 
    USUARIO_CIRURGIA, 
    USUARIO_CPF, 
    USUARIO_GENERO, 
    USUARIO_SENHA, 
    USUARIO_DATA_CRIACAO, 
    F_USUARIO_ID_USUARIO_PERFIL,
    F_USUARIO_ID_CLINICA,
    F_USUARIO_ID_REABILITACAO
) VALUES
  ('Administrador', 'admin.GP25ads@gmail.com', NULL, '11111111111', 'Masculino', 'adminGP25', NOW(), 1, 1, 1),
  ('Médico', 'medico.GP25ads@gmail.com', NULL, '22222222222', 'Masculino', 'medicoGP25', NOW(), 2, 1, 1),
  ('Paciente', 'paciente.GP25ads@gmail.com', NULL, '33333333333', 'Feminino', 'pacientegp25', NOW(), 3, 1, 1);
